spring.application.name=DATN1
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QUANLYVOTCAULONG;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=25092006
spring.jpa.show-sql=true